//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_PBL3.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public int ID_KH { get; set; }
        public Nullable<int> ID_LKH { get; set; }
        public string Ten_KH { get; set; }
        public string Diachi { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<double> Diemtichluy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual LOAI_KHACH_HANG LOAI_KHACH_HANG { get; set; }
    }
}
